SPECTRUM = "spectrum"
SPECTRUM_UNSUP = "spectrum_unsup"
LIFETIME = "lifetime"
LIFETIME_UNSUP = "lifetime_unsup"
SCATTERING = "scattering"
SCATTERING_UNSUP = "scattering_unsup"
SIZE = "size"
TIME_UNSUP = "time"

LEARNING_MODELS = [SPECTRUM, SPECTRUM_UNSUP, LIFETIME, LIFETIME_UNSUP, SCATTERING, SCATTERING_UNSUP, SIZE, TIME_UNSUP]
PLOTTING_MODELS = [SPECTRUM, LIFETIME, SCATTERING, SIZE]
TRAIN_MODELS = [SPECTRUM_UNSUP, LIFETIME_UNSUP, SCATTERING_UNSUP, SIZE]
